[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "0x50fa7b"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[colors.selection]
background = "0xff79c6"  # Cor de fundo rosa
text = "0x44475a"

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "none"
opacity = 0.8

[window.dimensions]
columns = 80
lines = 30

[window.padding]
x = 0
y = 0
